### ISSUE TITLE
Name of public key does not show when asking to remove in log level info

### ISSUE THREAD

**Issue by chris-scentregroup** [flaccid/akaudit#2]
Only in log level debug does it look like the user gets feedback on what the key is its asking the user to delete or not.

```
$ akaudit -i
INFO: interrogating user, flaccid
==> Remove key (y/n) ? n

INFO: audit complete.
```

**Comment by chris-scentregroup** [comment]
This is actually my fault by uncommenting https://github.com/flaccid/akaudit/blob/master/akaudit/audit.py#L98 in testing as it does not work in python3. I'll use this issue to do a slight update to ensure it works with python3.

**Comment by flaccid** [comment]
https://github.com/flaccid/akaudit/releases/tag/v0.2.1
